# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-31 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_model',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='basic_model',
            name='last_name',
        ),
    ]
